---
apiVersion: v2
name: omada-controller
version: 0.0.0
dependencies:
  - name: base
    version: 0.0.0
    repository: file://../../../../charts/base
  - name: omada-controller-helm
    alias: omada-controller
    version: 1.4.0
    repository: oci://mirror.gcr.io/mbentley
