---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/cloudnative-pg/0.28.2/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie@sha256:7a91b8daee8589f4825b50da23ed545b57c43a126016af573cbdf5e424d6c2f6
      extensions:
        - name: pgvector
          image:
            reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie@sha256:59e91a8f6cf16b3d3d28a5801ce339eac7de7cd2edb7b8f5ec6c1622dc4a2524
        - name: postgis
          image:
            reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.3-18-trixie@sha256:9bfd7b26d6d0e8a6ccf43a60a2320a2162e87cd29abd4d69312176eb1d711b44
          ld_library_path:
            - system
          env:
            - name: GDAL_DATA
              value: $${image_root}/share/gdal
            - name: PROJ_DATA
              value: $${image_root}/share/proj
        - name: vchord
          image:
            reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
          dynamic_library_path:
            - /usr/lib/postgresql/18/lib
          extension_control_path:
            - /usr/share/postgresql/18/
        - name: documentdb
          image:
            reference: ghcr.io/documentdb/documentdb-kubernetes-operator/documentdb:0.110.0
          dynamic_library_path: ["lib"]
          extension_control_path: ["share"]
          ld_library_path: ["lib", "system"]
        - name: timescaledb
          image: 
            reference: ghcr.io/m00nwtchr/timescaledb:2.27.0
            
      