---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatus-sidecar
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.1
    digest: sha256-89b422fd1ca9dfe8dac63a5ead498ff7c60b5a190902a7cb5b3d903685f08b2a
  url: oci://ghcr.io/home-operations/charts/gatus-sidecar
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/gatus-sidecar.*$"
