---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: towonel-config
  namespace: flux-system
spec:
  targetNamespace: towonel-operator
  dependsOn:
    - name: towonel-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/shared/towonel-operator/config
  commonMetadata:
    labels:
      app.kubernetes.io/name: towonel
