---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: donetick
  namespace: flux-system
spec:
  targetNamespace: donetick
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/donetick/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: donetick
