---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: omada-controller
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.3.0
    digest: sha256:ad4ee4810d8aac7eee66a59cb6e0c53b0be38666eb7c11ec08d608096579f503
  url: oci://mirror.gcr.io/mbentley/omada-controller-helm
  