---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  targetNamespace: volsync
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/volsync/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: volsync
