---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.9.0
    digest: sha256:0c15dc646896370ba587a95c81248be95bd490b257fbb73a897ad688e7f75b34
  url: oci://codeberg.org/towonel/charts/towonel-agent
