---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.4.1
    digest: sha256:de5602c06b0a31ea51a47d370e79a7990e6e05e84784145ea51f9edda9dab132
  url: oci://codeberg.org/towonel/charts/towonel-agent
