---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  targetNamespace: plugin-barman-cloud
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/plugin-barman-cloud/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: plugin-barman-cloud
