---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.4/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatus-sidecar
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.1
    digest: sha256:083f8cffd1aaaf7037afb910dece7dd238bf76b3936319ab1892eff6879b4dcf
  url: oci://ghcr.io/home-operations/charts/gatus-sidecar
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/gatus-sidecar.*$"
