---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatus-sidecar
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.3
    digest: sha256:13a260d3dfbce99f0468dd9bf5aa6c49556127b1064e94e3aa6f76f1947e0d5b
  url: oci://ghcr.io/home-operations/charts/gatus-sidecar
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/gatus-sidecar.*$"
