---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: miroir
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.11.13
    digest: sha256:b18cd79f8ae6030665d71841c197a09e203894281c43e837970e7fc046cd3409
  url: oci://ghcr.io/home-operations/charts/miroir
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token\\.actions\\.githubusercontent\\.com$"
        subject: "^https://github\\.com/home-operations/.*"
