---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/external-dns/1.20.0/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vps
spec:
  endpoints:
    - dnsName: vps.clerici.tech
      recordType: A
      targets:
        - ${NODE_V4_IP}
    - dnsName: vps.clerici.tech
      recordType: AAAA
      targets:
        - ${NODE_V6_IP}
