---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.2.3
    digest: sha256:d681e38a9762b33d3d79e232d1957e3d486d5fd590ba6ef9211dee2ddb3d49db
  url: oci://ghcr.io/kgateway-dev/charts/kgateway
