---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.3.1
    digest: sha256:ae0b886f2d7fb0c422b3b38d4cf60a931f7972c57eebf655762caa77edfd5bfb
  url: oci://ghcr.io/kgateway-dev/charts/kgateway
