---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-rules
  namespace: flux-system
spec:
  targetNamespace: node-feature-discovery
  dependsOn:
    - name: node-feature-discovery
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/node-feature-discovery/rules
  commonMetadata:
    labels:
      app.kubernetes.io/name: node-feature-discovery
