---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.4/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.4
    digest: sha256:afa59f5afcfffe21f8bfddb6606d9e2bfbf051d546f479b7b690bff444e2da68
  url: oci://ghcr.io/rook/rook-ceph
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/rook/rook.*$
