---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/pocket-id-operator/0.5.1/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: ${APP}
spec:
  logo:
    nameOverride: ${LOGO_NAME:=${APP}}
  clientID: ${APP}
  launchUrl: https://${APP_URL}
  pkceEnabled: ${OIDC_PKCE:=true}
  allowedUserGroups:
    - name: ${OIDC_GROUP:=admin}
      namespace: home-infra
