---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 1h
  chart:
    spec:
      chart: ./kubernetes/apps/home/prowlarr/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    timeout: 5m
    remediation:
      retries: 1
  upgrade:
    timeout: 5m
    remediation:
      retries: 1
  values:
    base:
      cnpg:
        enabled: true
        mode: restore
      externalSecret:
        enabled: true
      host: prowlarr.clerici.tech
      image:
        repository: ghcr.io/home-operations/prowlarr
        tag: 2.3.7.5365@sha256:b9557d772c974901aed9285189d904b613f1f07750fca930eecfe78544bd3d48
      ports:
        http: 9696
      env:
        PROWLARR__APP__INSTANCENAME: Prowlarr
        PROWLARR__APP__THEME: dark
        PROWLARR__AUTH__METHOD: External
        PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
        PROWLARR__LOG__DBENABLED: "False"
        PROWLARR__LOG__LEVEL: info
        PROWLARR__SERVER__PORT: 9696
        PROWLARR__POSTGRES__HOST:
          valueFrom:
            secretKeyRef:
              name: prowlarr-db-app
              key: pooler-host
        PROWLARR__POSTGRES__USER:
          valueFrom:
            secretKeyRef:
              name: prowlarr-db-app
              key: username
        PROWLARR__POSTGRES__PASSWORD:
          valueFrom:
            secretKeyRef:
              name: prowlarr-db-app
              key: password
        PROWLARR__POSTGRES__MAINDB:
          valueFrom:
            secretKeyRef:
              name: prowlarr-db-app
              key: dbname
      envFrom:
        - secretRef:
            name: prowlarr
      probes:
        liveness: &probes
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /ping
              port: 9696
        readiness: *probes
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          memory: 2Gi
      persistence:
        tmpfs:
          type: emptyDir
          globalMounts:
            - path: /config
              subPath: config
            - path: /tmp
              subPath: tmp
      createNamespace: false
