---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 84.4.0
    digest: sha256:fc55bfa4b8a73e0237d22b15cfa514219c6c8c8c95fc3b24ff34a2f0a871788e
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
