---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 84.3.0
    digest: sha256:302835c65c3e7d3bd450a7f0e26180cd6ef5eb4105095dd1fe920c66dcfb992e
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
