---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.2/helmrelease_v2.json?values=app-template/5.0.1
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  dependsOn:
    - name: blocky-resources
  values:
    controllers:
      blocky:
        strategy: RollingUpdate
        replicas: 3
        rollingUpdate:
          surge: 1
          unavailable: 1
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: blocky
                  topologyKey: kubernetes.io/hostname
          hostUsers: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile: {type: RuntimeDefault}
        containers:
          blocky:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.33.0@sha256:96c4ee1d4abee3e81475796403ffde0dfd0c53a6e263e2c35c867ba5563535d4
            env:
              PGCONNECT_TIMEOUT: 10
              PGHOST:
                valueFrom:
                  secretKeyRef:
                    name: blocky-postgres
                    key: host
              PGPORT:
                valueFrom:
                  secretKeyRef:
                    name: blocky-postgres
                    key: port
              PGUSER:
                valueFrom:
                  secretKeyRef:
                    name: blocky-postgres
                    key: username
              PGPASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: blocky-postgres
                    key: password
              PGDATABASE:
                valueFrom:
                  secretKeyRef:
                    name: blocky-postgres
                    key: dbname
            probes:
              readiness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /app/blocky
                      - healthcheck
              liveness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
    service:
      dns:
        controller: blocky
        type: LoadBalancer
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - "IPv4"
          - "IPv6"
        annotations:
          lbipam.cilium.io/ips: "${BLOCKY_LB_IP},${BLOCKY_LB_IPV6}"
          coredns.io/hostname: dot.clerici.tech
        ports: &p
          dns-tcp:
            port: 53
          dns-udp:
            port: 53
            protocol: UDP
          dns-tls:
            port: 853
      k8s:
        controller: blocky
        clusterIP: "${BLOCKY_CLUSTER_IP}"
        ports:
          <<: *p
          http:
            port: &port 4000
    serviceMonitor:
      blocky:
        serviceName: blocky-k8s
        endpoints:
          - port: http
    route:
      blocky-DOH:
        annotations:
          # google.com base64
          gatus.home-operations.com/endpoint: |-
            url: https://dns.clerici.tech/dns-query?dns=AAABAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ
        hostnames:
          - dns.clerici.tech
        parentRefs:
          - name: external
            namespace: kgateway
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /dns-query
            backendRefs:
              - identifier: k8s
                port: *port
    persistence:
      config:
        type: configMap
        name: blocky-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
      tls:
        type: secret
        name: blocky-tls
        globalMounts:
          - path: /certs/tls.crt
            subPath: tls.crt
          - path: /certs/tls.key
            subPath: tls.key
