---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-proxy-crowdsec-bouncer
  namespace: flux-system
spec:
  targetNamespace: envoy-proxy-crowdsec-bouncer
  dependsOn:
    - name: kgateway
      namespace: kgateway
  sourceRef:
    kind: OCIRepository
    name: envoy-proxy-crowdsec-bouncer
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: envoy-proxy-crowdsec-bouncer
