---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  targetNamespace: k8s-gateway
  sourceRef:
    kind: OCIRepository
    name: k8s-gateway
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: k8s-gateway
