---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.2.3
    digest: sha256:5171a4ddf7c7f52df363228b2513c3209734b05cf8a47bf67b2655280fa0d821
  url: oci://ghcr.io/jacaudi/charts/towonel-operator
