---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.5.0
    digest: sha256:9dc26e8a9b3118c7c9f99e87203b077c527b43510f23b9a6a68dec1e4de6e9e2
  url: oci://ghcr.io/jacaudi/charts/towonel-operator
