---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.4.1
    digest: sha256:e54d5be701d0acf4fa56ca5313c8b86fc9540607ea86762ba9fda1d3a2613ef9
  url: oci://ghcr.io/jacaudi/charts/towonel-operator
