---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.3/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-proxy-bouncer
spec:
  interval: 15m0s
  url: https://kdwils.github.io/envoy-proxy-crowdsec-bouncer
