---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.1/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.0
    digest: sha256:8f705a2490372ced4d911cfe414dc21a55cd846848b7a2abdb75f2e5557a0495
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/cloudnative-pg/charts.*$
