---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pocket-id-operator-main
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/aclerici38/pocket-id-operator.git
