---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.3/helmrelease_v2.json?values=pocket-id-operator/0.4.6
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    operator:
      args:
        - --zap-log-level=debug
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
    instance:
      name: pocket-id
      spec:
        image: ghcr.io/pocket-id/pocket-id:v2.5.0-distroless@sha256:deadc3c4dd6655a7d7f959200db1c74e394942dc061e6f3732b709983a08aab7
        route:
          enabled: true
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: external
              namespace: gateway-system
              sectionName: https
        encryptionKey:
          valueFrom:
            secretKeyRef:
              name: pocket-id
              key: ENCRYPTION_KEY
        databaseUrl:
          valueFrom:
            secretKeyRef:
              name: pocket-id-db-app
              key: uri
        appUrl: https://id.${SECRET_DOMAIN}
        hostUsers: false
        versionCheckDisabled: true
        fileBackend: database
        ui:
          sessionDuration: 1440
        smtp:
          host: smtp-relay.cluster-infra.svc.cluster.local
          from: bot@${SECRET_DOMAIN}
          port: 25
          tls: none
        emailNotifications:
          loginNotification: true
          oneTimeAccessAsAdmin: true
          apiKeyExpiration: true
          verification: true
        persistence:
          enabled: false
        metrics:
          enabled: true
          
      serviceMonitor:
        enabled: true
    users:
      - name: anthony
        spec:
          locale: en
          admin: true
          email: 
            valueFrom:
              key: EMAIL
              name: cluster-settings
          firstName: 
            value: Anthony
          lastName: 
            value: Clerici
      - name: steve
        spec:
          locale: en
          userInfoSecretRef:
            name: pocket-id-steve-info
    userGroups:
      - name: admin
        spec:
          users:
            userRefs:
              - name: anthony
          customClaims:
            - key: oc_groups
              value: opencloud-admins
            - key: immich_role
              value: admin
      - name: fam
        spec:
          users: &fam
            userRefs:
              - name: anthony
              - name: steve
            usernames:
              - melanie
      - name: all
        spec:
          users:
            <<: *fam
            userIDs:
              - 56f6f365-feb5-464f-bf31-f537d3a34a9e
          customClaims:
            - key: oc_groups
              value: opencloud-users
            - key: immich_role
              value: user
          