# Global mise config
[settings]
experimental = true

[env]
EDITOR = "nvim"
SOPS_AGE_KEY_FILE = "{{ env.HOME }}/home-ops/age.key"
TALOSCONFIG = "{{ env.HOME }}/home-ops/talos/home/clusterconfig/talosconfig"
ATUIN_SYNC_ADDRESS = "https://atuin.clerici.tech"

[tools]
"aqua:jdx/mise" = "2026.7.6"

# k8s
kubectl = "1.36.2"
helm = "4.2.3"
kustomize = "5.8.1"
flux2 = "2.9.2"
k9s = "0.51.0"
kind = "0.32.0"
kubebuilder = "4.15.0"
helmfile = "1.7.0"
helm-docs = "1.14.2"
cilium-cli = "0.19.6"
kubeconform = "0.8.0"

# Talos
talosctl = "1.13.6"
talhelper = "3.1.13"

# Tools
lefthook = "2.1.10"
yamllint = "1.38.0"
yamlfmt = "0.21.0"
actionlint = "1.7.12"
sops = "3.13.2"
age = "1.3.1"
zizmor = "1.27.0"
crane = "0.21.7"
mc = "latest"
gh = "2.96.0"
oci = "3.89.2"
jq = "1.8.2"
yq = "4.53.3"
go = "1.26.5"
uv = "0.11.28"
envsubst = "1.4.3"
claude-code = "2.1.210"
ffmpeg = "8.1.1"
neovim = "0.12.4"

"github:cloudnative-pg/cloudnative-pg" = { version = "1.30.0", exe = "kubectl-cnpg" }
"github:home-operations/yayamlls" = "0.1.14"
"github:home-operations/flate" = "v0.4.10"
