---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wyoming-piper
  namespace: flux-system
spec:
  targetNamespace: wyoming-piper
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/wyoming-piper/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: wyoming-piper
