---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/helmrelease_v2.json?values=app-template/4.6.2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dawarich
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      dawarich:
        pod:
          hostUsers: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          server: &container
            image:
              repository: mirror.gcr.io/freikin/dawarich
              tag: 1.6.1@sha256:a884f69f19ce0f66992f3872d24544d1e587e133b8a003e072711aafc1e02429
            command: ["web-entrypoint.sh"]
            args: ["bin/rails", "server", "-p", "3000", "-b", "::"]
            env: &env
              RAILS_ENV: production
              REDIS_URL: redis://dawarich-dragonfly-db:6379
              TIME_ZONE: ${TZ}
              PROMETHEUS_EXPORTER_ENABLED: true
              PROMETHEUS_EXPORTER_HOST: 0.0.0.0
              APPLICATION_HOSTS: ${APP_URL}
              DISTANCE_UNIT: mi
              STORE_GEODATA: true
              RAILS_CACHE_DB: 0
              RAILS_JOB_QUEUE_DB: 0
              RAILS_WS_DB: 0
              SMTP_SERVER: smtp-relay.cluster-infra
              SMTP_PORT: 25
              SMTP_FROM: bot@${SECRET_DOMAIN}
              SECRET_KEY_BASE:
                secretKeyRef:
                  name: dawarich
                  key: SECRET_KEY_BASE
              
              DATABASE_HOST:
                secretKeyRef:
                  name: dawarich-db-app
                  key: host
              DATABASE_USERNAME:
                secretKeyRef:
                  name: dawarich-db-app
                  key: user
              DATABASE_PASSWORD:
                secretKeyRef:
                  name: dawarich-db-app
                  key: password
              DATABASE_NAME:
                secretKeyRef:
                  name: dawarich-db-app
                  key: dbname

              OIDC_CLIENT_ID:
                secretKeyRef:
                  name: dawarich-oidc-credentials
                  key: client_id
              OIDC_CLIENT_SECRET:
                secretKeyRef:
                  name: dawarich-oidc-credentials
                  key: client_secret
              OIDC_ISSUER:
                secretKeyRef:
                  name: dawarich-oidc-credentials
                  key: issuer_url
              OIDC_REDIRECT_URI: https://${APP_URL}/users/auth/openid_connect/callback
              OIDC_PROVIDER_NAME: Pocket-ID
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &port 3000
                    path: /api/v1/health
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
          sidekiq:
            <<: *container
            command: ["sidekiq-entrypoint.sh"]
            args: ["bundle exec sidekiq"]
            env:
              <<: *env
              PROMETHEUS_EXPORTER_HOST: 127.0.0.1
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
    service:
      dawarich:
        controller: dawarich
        ports:
          http:
            port: *port
          metrics:
            port: 9394
    serviceMonitor:
      dawarich:
        serviceName: dawarich
        endpoints:
          - port: metrics
            scheme: http
    route:
      dawarich:
        hostnames:
          - dawarich.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: gateway-system
    persistence:
      data:
        existingClaim: dawarich
        globalMounts:
          - path: /var/app/storage
            subPath: storage
          - path: /var/app/public
            subPath: public
          # ruby won't let tmp dir be world-writeable so can't be emptydir
          - path: /tmp
            subPath: tmp
      tmpfs:
        type: emptyDir
        globalMounts:
          # something for pg migrations?
          - path: /var/app/db
            subPath: db
          - path: /var/app/tmp
            subPath: app_tmp
