---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pocket-id-raphael
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: anthony-raphael-key
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: pocket-id-raphael
          property: INSTANCE_API_KEY
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pocket-id-cloud
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: anthony-cloud-key
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: pocket-id-cloud
          property: INSTANCE_API_KEY
