---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/renovate-operator/6.0.0/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: ${NAME}
spec:
  provider:
    name: github
  discoveryFilters:
    - /aclerici38\/(${REPOS})/
  renovateConfig:
    inline: |
      module.exports = {
        allowedCommands: ['pnpm run bundle'],
        allowedUnsafeExecutions: ['mise'],
        customEnvVariables: {MISE_TRUSTED_CONFIG_PATHS: '/tmp/repos'},
        hostRules: [
          {
            hostType: 'docker',
            matchHost: 'docker.io',
            username: process.env.DOCKERHUB_USERNAME,
            password: process.env.DOCKERHUB_TOKEN,
          },
        ],
        platformCommit: 'enabled',
        redisUrl: 'redis://renovate-operator-dragonfly-db:6379',
      };
  extraEnv:
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: renovate-operator
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-operator
          key: DOCKERHUB_TOKEN
  image: ghcr.io/renovatebot/renovate:44.30.4@sha256:e28fae22baff685b0c4d00277500b41886ff457bb6f89d7d08eaf82c95fae442
  parallelism: 1
  scratchVolume:
    medium: Memory
    sizeLimit: 4Gi
  resources:
    requests:
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 5Gi
  schedule: "${SCHEDULE}"
  githubAppReference:
    secretName: renovate-operator
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
