---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/external-secrets/2.3.0/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-kiosk-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        config.yaml: |
          weather:
            locations:
              - name: {{ .HOME_CITY }}
                lat: {{ .HOME_LAT }}
                lon: {{ .HOME_LON }}
                api: {{ .WEATHER_API_KEY }}
                unit: imperial
                lang: en
                default: true
                round_temperature: true
                show:
                  humidity: true
                  wind: true
                  visibility: true
  dataFrom:
    - extract:
        key: immich-kiosk
