---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/perfectra1n-volsync/0.18.5/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: versity
spec:
  enabled: true
  trigger:
    schedule: 30 3,15 * * *
  repository:
    repository: volsync-kopia-versity