---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.32
    digest: sha256:04eef966b9024178c836ce82b833acf6e0771fb2dd9d5063c61ff024c988abcc
  url: oci://codeberg.org/towonel/charts/towonel-agent
