---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-clusterissuers
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/shared/cert-manager/clusterissuers
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager
