---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-proxy-crowdsec-bouncer
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.8.2
    digest: sha256:4fbc7b936f6161cb98df73b478008e1e6faf43f620bf6dbe516b104682c17df8
  url: oci://ghcr.io/kdwils/charts/envoy-proxy-bouncer
