---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.4/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-proxy-crowdsec-bouncer
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.2
    digest: sha256:6c7345db1b6dfa98edf3b4e18ceb3b05e6513a7a1f67d561eb84add5e5ef273a
  url: oci://ghcr.io/kdwils/charts/envoy-proxy-bouncer
