---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.6.0
    digest: sha256:b37497f4614678c20ebd8e9c93a6fe98f106022fe945bd6fac2ed7acd3fce04d
  url: oci://ghcr.io/jacaudi/charts/towonel-operator
