---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
  namespace: flux-system
spec:
  targetNamespace: seerr
  sourceRef:
    kind: OCIRepository
    name: seerr
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: seerr
