---
apiVersion: v2
name: node-feature-discovery
version: 0.0.0
dependencies:
  - name: base
    version: 0.0.0
    repository: file://../../charts/base
  - name: node-feature-discovery
    version: 0.18.3
    repository: oci://registry.k8s.io/nfd/charts
