---
base:
  app-template:
    enabled: false

node-feature-discovery:
  master:
    hostUsers: false
  gc:
    hostUsers: false
  worker:
    hostUsers: false
    config:
      core:
        labelSources:
          - pci
          - system
          - usb
      sources:
        custom:
          - name: intel.gpu
            labels:
              intel.feature.node.kubernetes.io/gpu: "true"
            matchFeatures:
              - feature: pci.device
                matchExpressions:
                  vendor: {op: In, value: ["8086"]}
                  class: {op: In, value: ["0300", "0380"]}
  prometheus:
    enable: true
    scrapeInterval: 1m
