---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.3/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: patch
spec:
  patches:
    # https://blog.ferretdb.io/run-ferretdb-postgres-documentdb-extension-cnpg-kubernetes/
    # extensions initialized in the database CR
    - patch: |-
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: patch
        spec:
          managed:
            roles:
              - name: app
                login: true
                inRoles:
                  - documentdb_admin_role
          postgresql:
            pg_hba:
              # pg_cron and documentdb background workers connect via localhost
              - host app postgres localhost trust
              - host app documentdb_bg_worker_role localhost trust
            shared_preload_libraries:
              - pg_cron
              - pg_documentdb_core
              - pg_documentdb
            parameters:
              max_connections: "200"
              # https://github.com/FerretDB/FerretDB/issues/5284#issuecomment-3326399933
              cron.database_name: 'app'
              documentdb.bg_worker_database_name: 'app'
              documentdb.enableBackgroundWorker: 'true'
              documentdb.enableBackgroundWorkerJobs: 'true'
              documentdb.enableCompact: 'true'
              documentdb.enableLetAndCollationForQueryMatch: 'true'
              documentdb.enableNowSystemVariable: 'true'
              documentdb.enableSortbyIdPushDownToPrimaryKey: 'true'
              documentdb.enableSchemaValidation: 'true'
              documentdb.enableBypassDocumentValidation: 'true'
              documentdb.enableUserCrud: 'true'
              documentdb.maxUserLimit: '100'
            extensions:
              - name: documentdb
                image:
                  reference: ghcr.io/documentdb/documentdb-kubernetes-operator/documentdb:0.1.1-test
                dynamic_library_path: ["lib"]
                extension_control_path: ["share"]
                ld_library_path: ["lib", "system"]
      target:
        kind: Cluster