---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.4
    digest: sha256:c5c59025e673a75d2ef7c569675ae467f35e78e136f5e6641b9f1ffee84fe902
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
