---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.1
    digest: sha256:674c410544626e2ab727874fb06d46c3de6496337b38fa5156485e67c43794cf
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
