---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
spec:
  targetNamespace: renovate-operator
  path: ./kubernetes/apps/tools/renovate-operator/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-auth
spec:
  targetNamespace: renovate-operator
  dependsOn:
    - name: renovate-operator
  path: ./kubernetes/apps/tools/renovate-operator/resources
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-30-min
spec:
  targetNamespace: renovate-operator
  dependsOn:
    - name: renovate-operator-auth
  path: ./kubernetes/apps/tools/renovate-operator/jobs
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  postBuild:
    substitute:
      NAME: 30-min
      SCHEDULE: "'*/30 * * * *'"
      REPOS: "home-ops|pocket-id-operator|containers"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-15-min
spec:
  targetNamespace: renovate-operator
  dependsOn:
    - name: renovate-operator-auth
  path: ./kubernetes/apps/tools/renovate-operator/jobs
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  postBuild:
    substitute:
      NAME: 15-min
      SCHEDULE: "'*/15 * * * *'"
      REPOS: "k8s-versioned-schemas|pocket-id-go-client|workflows"
