---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/helmrelease_v2.json?values=app-template/4.6.2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      frigate:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: frigate-gpu
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: Unconfined }
        containers:
          frigate:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.17.1@sha256:1724960349dad0bd2ae8ec884171a6fd5755a4dc242a0e66cadbda9c0e85c99b
            env:
              YOLO_MODELS: yolov7x-320
              HF_HOME: /tmp
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
              S6_READ_ONLY_ROOT: 1
            envFrom:
              - secretRef:
                  name: frigate
            securityContext:
              allowPrivilegeEscalation: false
              # Frigate does in-place nginx config editing, so no true readonly root fs
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  # S6
                  - CHOWN
                  - SETUID
                  - SETGID
                  - FOWNER
                  - DAC_OVERRIDE
                  - PERFMON
            resources:
              requests:
                cpu: 2000m
                memory: 2Gi
              limits:
                memory: 16Gi
              claims:
                - name: gpu
    service:
      frigate:
        controller: frigate
        type: ClusterIP
        ports:
          http:
            port: 5000
          http-auth:
            primary: true
            port: &auth 8971
          rtsp:
            port: 8554
          webrtc:
            port: 8555
    route:
      auth:
        hostnames:
          - ${APP_URL}
        parentRefs:
          - name: external
            namespace: gateway-system
        rules:
          - backendRefs:
            - identifier: frigate
              port: *auth
    persistence:
      config:
        existingClaim: frigate
      media:
        existingClaim: frigate-media
        globalMounts:
          - path: /media/frigate
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /run
            subPath: run
          - path: /tmp
            subPath: tmp
          - path: /dev/shm
            subPath: shm
          - path: /etc/letsencrypt
            subPath: letsencrypt
