---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trek
  namespace: flux-system
spec:
  targetNamespace: trek
  sourceRef:
    kind: OCIRepository
    name: trek
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: trek
