---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nats-opencloud
  namespace: flux-system
  labels:
    app.kubernetes.io/name: nats-opencloud
    dormammu.internal/managed: "true"
spec:
  interval: 1h
  url: oci://ghcr.io/aclerici38/home-ops/nats-opencloud
  ref:
    tag: main
  layerSelector:
    mediaType: application/vnd.cncf.flux.content.v1.tar+gzip
    operation: extract
