---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-30-min
  namespace: flux-system
spec:
  targetNamespace: renovate-operator
  dependsOn:
    - name: renovate-operator-auth
  sourceRef:
    kind: OCIRepository
    name: renovate-operator
  path: ./jobs
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  postBuild:
    substitute:
      NAME: 30-min
      SCHEDULE: "'*/30 * * * *'"
      REPOS: "home-ops|pocket-id-operator|containers"
