---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-auth
  namespace: flux-system
spec:
  targetNamespace: renovate-operator
  dependsOn:
    - name: renovate-operator
  sourceRef:
    kind: OCIRepository
    name: renovate-operator
  path: ./resources
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator-auth
