---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  FLUX_PATH: kubernetes/flux/cloud
  CLUSTER_NAME: cloud
  SECRET_DOMAIN: clerici.tech
  EXTERNAL_DOMAIN: cloud.clerici.tech
  NODE_V4_IP: 192.9.147.24
  NODE_V6_IP: 2603:c024:c01e:3c40:0:ed89:a4b3:3d24
  TZ: America/Los_Angeles
  COREDNS_CLUSTER_IP: "172.17.0.10"
  # renovate: datasource=github-releases depName=siderolabs/talos
  TALOS_VERSION: v1.13.7
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  KUBE_VERSION: v1.36.3
