---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  FLUX_PATH: kubernetes/flux/cloud
  CLUSTER_NAME: cloud
  SECRET_DOMAIN: clerici.tech
  NODE_IP: 192.9.147.24
  TZ: America/Los_Angeles
  COREDNS_CLUSTER_IP: "172.17.0.10"
  TOWONEL_API_URL: http://towonel-node.towonel-node:8443
