---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dawarich
spec:
  path: ./kubernetes/apps/home-infra/dawarich/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: dawarich
