---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=dawarich
      - OIDC_GROUP=fam
      - OIDC_PKCE=false
patches:
  - path: ./patch.yaml
    target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
components:
  - ../../../components/ks/app
  - ../../../components/kustomize/external-secret
  - ../../../components/kustomize/cnpg/init
  - ../../../components/kustomize/cnpg/extensions
  - ../../../components/kustomize/pocket-id
  - ../../../components/kustomize/dragonfly
  - ../../../components/kustomize/volsync/cephfs
