---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  targetNamespace: mosquitto
  sourceRef:
    kind: OCIRepository
    name: mosquitto
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: mosquitto
