---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/towonel-operator/1.0.1/towonelagent_v1alpha1.json
apiVersion: towonel.io/v1alpha1
kind: TowonelAgent
metadata:
  name: ${CLUSTER_NAME}
spec:
  relayUrl: https://vps.clerici.tech:8444
  tunnelRef:
    name: ${CLUSTER_NAME}-k8s
    namespace: towonel-operator
  workload:
    replicas: 1
    image: codeberg.org/towonel/towonel-agent:0.2.2@sha256:9a749db23ce3cf4c208fe3d275b5857d57b15744a291efca751dc0c3e6f604fc
