---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/towonel-operator/1.0.1/towonelagent_v1alpha1.json
apiVersion: towonel.io/v1alpha1
kind: TowonelAgent
metadata:
  name: ${CLUSTER_NAME}
spec:
  relayUrl: https://vps.clerici.tech:8444
  tunnelRef:
    name: ${CLUSTER_NAME}-k8s
    namespace: towonel-operator
  workload:
    replicas: 1
    image: codeberg.org/towonel/towonel-agent:1.0.0@sha256:ee8eea6accaec4dd9f747b51dc862d3107b8121493ba505a2aed019b95800737
