---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-base
  namespace: flux-system
spec:
  targetNamespace: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/shared/kube-prometheus-stack/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: kube-prometheus-stack
