---
apiVersion: v1
kind: Service
metadata:
  name: opensprinkler
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opensprinkler-1
  labels:
    kubernetes.io/service-name: opensprinkler
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - 10.0.80.185
---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/kgateway/2.3.4/trafficpolicy_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: opensprinkler-strip-headers
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: opensprinkler
  headerModifiers:
    request:
      remove:
        - cookie
---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/gateway-api/1.5.1/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opensprinkler
  annotations:
    towonel.io/tunnel: enable
    towonel.io/tunnel-ref: towonel-operator/${CLUSTER_NAME}-k8s
    towonel.io/agent-ref: ${CLUSTER_NAME}
spec:
  hostnames:
    - h2o.clerici.tech
  parentRefs:
    - name: external
      namespace: kgateway
      sectionName: https
  rules:
    - timeouts:
        request: 0s
        backendRequest: 0s
      backendRefs:
        - name: opensprinkler
          port: 80
