---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filebrowser
  namespace: flux-system
spec:
  targetNamespace: filebrowser
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/filebrowser/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: filebrowser
