---
apiVersion: v2
name: nats-opencloud
version: 0.0.0
dependencies:
  - name: base
    version: 0.0.0
    repository: file://../../../../charts/base
  - name: nats
    version: 2.14.0
    repository: https://nats-io.github.io/k8s/helm/charts/
