---
base:
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
  ports:
    http: 8191
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /health
          port: 8191
    readiness: *probes
  securityContext:
    # TODO: test RO root fs
    readOnlyRootFilesystem: false
  resources:
    requests:
      cpu: 10m
      memory: 150Mi
    limits:
      memory: 2Gi
  persistence:
    tmpfs:
      type: emptyDir
      globalMounts:
        - path: /tmp
          subPath: tmp
        - path: /app/.local
          subPath: local
