---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-node
spec:
  chartRef:
    kind: OCIRepository
    name: towonel-node
  interval: 30m
  dependsOn:
    - name: towonel-node-resources
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TOWONEL_HUB_DB_DRIVER: postgres
              TOWONEL_HUB_PUBLIC_URL: https://towonel.clerici.tech
              TOWONEL_HUB_RELAY_URL: &iroh https://vps.clerici.tech:8444
              TOWONEL_EDGE_RELAY_URL: *iroh
              TOWONEL_EDGE_ADVERTISED_ADDRESSES: vps.clerici.tech:443
              TOWONEL_EDGE_REGION: CA
              TOWONEL_HUB_DB_DSN:
                secretKeyRef:
                  name: towonel-node-db-app
                  key: uri
              TOWONEL_IDENTITY_KEY:
                secretKeyRef:
                  name: towonel-node
                  key: TOWONEL_IDENTITY_KEY
              TOWONEL_HUB_OPERATOR_API_KEY:
                secretKeyRef:
                  name: towonel-node
                  key: TOWONEL_HUB_OPERATOR_API_KEY
              TOWONEL_HUB_KEK:
                secretKeyRef:
                  name: towonel-node
                  key: TOWONEL_HUB_KEK
              TOWONEL_INVITE_HASH_KEY:
                secretKeyRef:
                  name: towonel-node
                  key: TOWONEL_INVITE_HASH_KEY
              TOWONEL_HUB_LINK_PSK:
                secretKeyRef:
                  name: towonel-node
                  key: TOWONEL_HUB_LINK_PSK
    route:
      towonel-node:
        annotations:
          towonel.io/tunnel: enable
        hostnames:
          - towonel.clerici.tech
        parentRefs:
          - name: external
            namespace: kgateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: 8443
    serviceMonitor:
      main:
        enabled: true
    monitoring:
      prometheusrule:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            grafana.internal/instance: grafana
