---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-node
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.4.1
    digest: sha256:f425bfef5a810d21ec867502869fb085dd3a9a277a22bd73bc150042bb5951b2
  url: oci://codeberg.org/towonel/charts/towonel-node
