---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-node
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.11.0
    digest: sha256:76964baf0ef2786acbd97dfe622ac06f77c9f19f266a230a804bb5e3306aab0c
  url: oci://git.ow-ops.eu/towonel/charts/towonel-node
