---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-node
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.11.2
    digest: sha256:88d2288633b6297d88324f521817c2febcdc1ea63972823e70d15156537cb5b2
  url: oci://git.ow-ops.eu/towonel/charts/towonel-node
