---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.2/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-kiosk
  namespace: flux-system
spec:
  targetNamespace: immich-kiosk
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/immich-kiosk/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich-kiosk
