---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: ./patch.yaml
    target:
      kind: HelmRelease
  - patch: |-
      - op: add
        path: /spec/postRenderers/-
        value:
          kustomize:
            patches:
              - patch: |
                  - op: add
                    path: /spec/rules/0/timeouts
                    value:
                      request: 0s
                target:
                  group: gateway.networking.k8s.io
                  kind: HTTPRoute
    target:
      kind: HelmRelease
