---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux-operator/0.45.0/values.schema.json
serviceMonitor:
  create: true
installCRDs: true
web:
  networkPolicy:
    create: false
securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
  seccompProfile:
    type: "RuntimeDefault"
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 64Mi
