---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: ${VOLSYNC_SCHEDULE="0 */12 * * *"}
  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    compression: zstd-best-compression
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
      fsGroupChangePolicy: ${VOLSYNC_FSGROUPCHANGEPOLICY:=OnRootMismatch}
    parallelism: 2
    repository: ${VOLSYNC_KOPIA_REPO:=volsync-kopia-versity}
    retain:
      hourly: 24
      daily: 7
    storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}
    cacheStorageClassName: ${VOLSYNC_CACHE_STORAGECLASS:=ceph-filesystem}
    cacheCapacity: ${VOLSYNC_CACHE_CAPACITY:=5Gi}
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODE:=ReadWriteOnce}"]
    