---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  targetNamespace: openebs-system
  dependsOn:
    - name: openebs-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/cloud/openebs-system/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: openebs
