---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-pvc-backup
  namespace: nfs-server
spec:
  targetNamespace: nfs-server
  path: ./kubernetes/components/volsync/resources/backup
  dependsOn:
    - name: volsync
      namespace: flux-system
    - name: external-secrets
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  prune: true
  interval: 30m
  timeout: 3m
  postBuild:
    substitute:
      APP: immich
      VOLSYNC_SCHEDULE: 0 4 * * *
      VOLSYNC_KOPIA_REPO: volsync-kopia-backblaze
      VOLSYNC_STORAGECLASS: zfs-tank
      VOLSYNC_SNAPSHOTCLASS: openebs-zfs
      VOLSYNC_CACHE_STORAGECLASS: zfs-ssd
      VOLSYNC_CACHE_CAPACITY: 100Gi
