---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-proxy-crowdsec-bouncer
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.2
    digest: sha256:e20c86d732bb9801f98841ae1525fa169421e9d8ae5fb76be3a92ef574231abc
  url: oci://ghcr.io/kdwils/charts/envoy-proxy-bouncer
