---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-proxy-crowdsec-bouncer
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.0
    digest: sha256:b4a41ae669044f1325025a96773f04a139976b97455cf47f0285ba3c95305d15
  url: oci://ghcr.io/kdwils/charts/envoy-proxy-bouncer
