---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/pocket-id-operator/0.14.3/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: open-webui-home-assistant
spec:
  name: open-webui (Home Assistant)
  # Must equal this backend's tool server info.id
  clientID: open-webui-home-assistant
  pkceEnabled: true
  callbackUrls:
    - https://chat.clerici.tech/oauth/clients/mcp:open-webui-home-assistant/callback
  secret:
    additionalLabels:
      external-secrets.io/type: webhook
  apiAccess:
    - apiRef:
        name: mcp
        namespace: envoy-gateway
      delegatedPermissions:
        - home-assistant
