---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.1.0
    digest: sha256:a20f591a3dff489304a04f1543fbb1c8f2a1a34e46ce7b930ebb7aa22e13f7e4
  url: oci://ghcr.io/jacaudi/charts/towonel-operator
