---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: samba
  namespace: flux-system
  labels:
    app.kubernetes.io/name: samba
    oci.home/managed: "true"
spec:
  interval: 1h
  url: oci://ghcr.io/aclerici38/home-ops/samba
  ref:
    tag: main
  layerSelector:
    mediaType: application/vnd.cncf.flux.content.v1.tar+gzip
    operation: extract
