---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  targetNamespace: sonarr
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/sonarr/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: sonarr
