---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-scrubber-ssd
  namespace: flux-system
spec:
  targetNamespace: zfs-scrubber
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/zfs-scrubber/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: zfs-scrubber
  postBuild:
    substitute:
      POOL: ssd
      SCRUB_SCHEDULE: "0 0 1,15 * *"
