---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.2/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crowdsec-chart
spec:
  interval: 1h
  ref:
    commit: 22a259ff417759a2bea2d64f4be4c56547d66dc6
  url: https://github.com/aclerici38/crowdsec-chart
