---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: crowdsec
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.23.0
    digest: sha256:0ab1a47b9a1c8eef3f0b23aaca819eff3080dcb8d8ac77082e849d17ca2e2091
  url: oci://ghcr.io/crowdsecurity/helm-charts/crowdsec
