---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.7.1
    digest: sha256:e7ad60868170955f0d8d4771558026e29078c8ae7bb300926b83f793b2729aaf
  url: oci://ghcr.io/jacaudi/charts/towonel-operator
