---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: crowdsec
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.24.0
    digest: sha256:a2c4fbf4f4692d9fca09d51d102c7e417fbe93b609356c4777f9cc31cb202458
  url: oci://ghcr.io/crowdsecurity/helm-charts/crowdsec
