---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.2.3
    digest: sha256:e7fd5d57b5e3e8ea405ca9329581e4b6cc4ba3ca9da842ff2c12a63b670f2ef5
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
