---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.3.1
    digest: sha256:46910483ac4b7a8f769db2407fd0c86e8a4d5c3bd9797db13b2b1c76a2dcbeb7
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
