{{- define "base.externalSecret.spec" -}}
{{- $es := .es -}}
{{- $key := .key -}}
secretStoreRef:
  kind: ClusterSecretStore
  name: {{ $es.store }}
{{- if $es.data }}
data:
{{- toYaml $es.data | nindent 2 }}
{{- else }}
dataFrom:
  - extract:
      key: {{ $key }}
{{- end }}
{{- end -}}

{{- if .Values.externalSecret.enabled }}
{{- $es := .Values.externalSecret -}}
{{- $name := $es.name | default .Release.Name -}}
{{- $key  := $es.key  | default .Release.Name -}}

{{- if $es.namespaceSelectors }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ $name }}
spec:
  refreshTime: 1m
  externalSecretName: {{ $name }}
  namespaceSelectors:
    {{- toYaml $es.namespaceSelectors | nindent 4 }}
  externalSecretSpec:
    {{- include "base.externalSecret.spec" (dict "es" $es "key" $key) | nindent 4 }}
{{- else }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  {{- include "base.externalSecret.spec" (dict "es" $es "key" $key) | nindent 2 }}
{{- end }}
{{- end }}
