{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- with .Values.extraNamespaceLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    {{- if .Values.cnpg.enabled }}
    dormammu.io/cnpg-cluster: "true"
    {{- end }}
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: {{ .Values.psa | default "restricted" | quote }}
    pod-security.kubernetes.io/audit: {{ .Values.psa | default "restricted" | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.psa | default "restricted" | quote }}
  {{- with .Values.extraNamespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
