---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/cloudnative-pg/0.29.0/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie-documentdb
spec:
  images:
    # DocumentDB doesn't immediately support new postgres versions apparently
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie
      extensions:
        - name: documentdb
          image:
            reference: ghcr.io/documentdb/documentdb-kubernetes-operator/documentdb:0.114.0
          dynamic_library_path:
            - "lib"
          extension_control_path:
            - "share"
          ld_library_path:
            - "lib"
            - "system"
