---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/cloudnative-pg/0.28.3/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie
      extensions:
        - name: pgvector
          image:
            reference: ghcr.io/cloudnative-pg/pgvector:0.8.4-18-trixie
        - name: postgis
          image:
            reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.4-18-trixie
          ld_library_path:
            - system
          env:
            - name: GDAL_DATA
              value: $${image_root}/share/gdal
            - name: PROJ_DATA
              value: $${image_root}/share/proj
        - name: vchord
          image:
            reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
          dynamic_library_path:
            - /usr/lib/postgresql/18/lib
          extension_control_path:
            - /usr/share/postgresql/18/
        - name: documentdb
          image:
            reference: ghcr.io/documentdb/documentdb-kubernetes-operator/documentdb:0.110.0
          dynamic_library_path:
            - "lib"
          extension_control_path:
            - "share"
          ld_library_path:
            - "lib"
            - "system"
