---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/refs/heads/main/dist/schemas/helmrelease_v2_pocket-id-operator.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  valuesFrom:
    - kind: ConfigMap
      name: pocket-id-operator-values
      valuesKey: values.yaml
  values:
    pocket-id-instance:
      instance:
        enabled: true
        spec:
          external:
            url: https://id.clerici.tech
            apiKeySecretRef:
              name: pocket-id-operator
              key: INSTANCE_API_KEY
      userGroups:
        - name: admin
          spec:
            customClaims:
              - key: oc_groups
                value: opencloud-admins
              - key: immich_role
                value: admin
              - key: frigate_role
                value: admin
