---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/external-secrets/2.10.0/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - secretKey: SONARR__AUTH__APIKEY
      remoteRef:
        key: sonarr
        property: SONARR__AUTH__APIKEY
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: radarr
        property: RADARR__AUTH__APIKEY
    - secretKey: SONARR_RAPHAEL__AUTH__APIKEY
      remoteRef:
        key: sonarr-raphael
        property: SONARR__AUTH__APIKEY
    - secretKey: RADARR_RAPHAEL__AUTH__APIKEY
      remoteRef:
        key: radarr-raphael
        property: RADARR__AUTH__APIKEY
