{{- if hasKey .Values "dragonfly" }}
{{- $app := include "resources.app" . -}}
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ $app }}-dragonfly-db
spec:
  {{- include "resources.mergeSpec" (list (include "resources.dragonfly.spec" .) (dig "spec" dict .Values.dragonfly)) | nindent 2 }}
{{- end }}
