{{- if hasKey .Values "dragonfly" }}
{{- $app := include "resources.app" . -}}
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ $app }}-dragonfly-db
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.39.0@sha256:0fa01a2b929e704c7a9300d23e7f52002ebd39e90996fb8bb63826aed92fa06f
  replicas: 3
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --dbnum=1
    - --dbfilename=
    - --proactor_threads=4
    - --version_check=false
    - --cluster_mode=emulated
    - --lock_on_hashtags
    {{- range .Values.dragonfly.extraArgs }}
    - {{ . }}
    {{- end }}
  resources:
    requests: {cpu: 100m}
    limits: {memory: 1Gi}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
{{- end }}
