{{- if hasKey .Values "externalSecret" }}
{{- $app := include "resources.app" . -}}
{{- $es := .Values.externalSecret -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $app }}
  labels:
    dormammu.internal/component: external-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  {{- with $es.data }}
  data: {{ toYaml . | nindent 4 }}
  {{- end }}
  dataFrom:
    - extract:
        key: {{ dig "key" $app $es }}
{{- end }}
