{{- if hasKey .Values "externalSecret" }}
{{- $app := include "resources.app" . -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $app }}
  labels:
    dormammu.internal/component: external-secret
spec:
  {{- include "resources.mergeSpec" (list (include "resources.externalSecret.spec" .) (dig "spec" dict .Values.externalSecret)) | nindent 2 }}
{{- end }}
