{{- if hasKey .Values "gpu" }}
{{- $app := include "resources.app" . -}}
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: {{ $app }}-gpu
spec:
  {{- include "resources.mergeSpec" (list (include "resources.gpu.spec" .) (dig "spec" dict .Values.gpu)) | nindent 2 }}
{{- end }}
