{{- if hasKey .Values "nfs" }}
{{- $app := include "resources.app" . -}}
{{- $replicas := dig "replicas" 1 .Values.nfs -}}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $app }}
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  pollingInterval: 10
  cooldownPeriod: 0
  idleReplicaCount: 0
  minReplicaCount: {{ $replicas }}
  maxReplicaCount: {{ $replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $app }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
        query: max(kube_pod_status_ready{namespace="storage",pod=~"nfs-server-.*",condition="true"}) OR on() vector(0)
        threshold: "1"
{{- end }}
