{{- if hasKey .Values "oidc" }}
{{- $app := include "resources.app" . -}}
{{- $spec := dig "spec" dict .Values.oidc -}}
{{- if include "resources.oidc.needsBackend" . }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ $app }}-oidc-backend
spec:
  {{- include "resources.mergeSpec" (list (include "resources.oidc.backendSpec" .) (dig "backend" dict $spec)) | nindent 2 }}
{{- end }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $app }}-oidc
spec:
  {{- include "resources.mergeSpec" (list (include "resources.oidc.securityPolicySpec" .) (dig "securityPolicy" dict $spec)) | nindent 2 }}
{{- end }}
