{{- if hasKey .Values "pocketId" }}
{{- $app := include "resources.app" . -}}
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: {{ $app }}
spec:
  {{- include "resources.mergeSpec" (list (include "resources.pocketId.spec" .) (dig "spec" dict .Values.pocketId)) | nindent 2 }}
{{- end }}
