---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: smartctl-exporter
  namespace: flux-system
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/aclerici38/home-ops/smartctl-exporter
  ref:
    tag: main
  layerSelector:
    mediaType: application/vnd.cncf.flux.content.v1.tar+gzip
    operation: extract
