---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  targetNamespace: plugin-barman-cloud
  sourceRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: plugin-barman-cloud
