---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.0
    digest: sha256:ba56b43343d5803dff49d5085e0c6a58725f3727c3f574d13c3aff31abfe4c89
  url: oci://ghcr.io/home-operations/charts/tuppr
