---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.36
    digest: sha256:1cdec8c8d9f2a7afda0f5d52769d01f59fe117199592a94f380646e6e6d77614
  url: oci://ghcr.io/home-operations/charts/tuppr