---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: towonel-agent
  namespace: flux-system
spec:
  targetNamespace: towonel
  dependsOn:
    - name: towonel-agent-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/cloud/towonel/agent
  commonMetadata:
    labels:
      app.kubernetes.io/name: towonel-agent
