---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.2/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
  namespace: flux-system
spec:
  targetNamespace: renovate-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/cloud/renovate-operator/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
