---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.6.1
    digest: sha256:6eb6dfdbaa0f35a3bd8d0a3aa8faf7d02588bd0395bf6fe6faaa6902b15fb49d
  url: oci://codeberg.org/towonel/charts/towonel-agent
