---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.2.0
    digest: sha256:8119d4ebf2c6796fcb01ad548d9fa776355095aadbf8f464d0587232ed67b873
  url: oci://codeberg.org/towonel/charts/towonel-agent
