---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.5.1
    digest: sha256:333effd7fab3cd533d55dbd1277e816e11a0e79484946d08733de227aff001d1
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/towonel-agent
