---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/towonel-operator/1.0.1/towonelagent_v1alpha1.json
apiVersion: towonel.io/v1alpha1
kind: TowonelAgent
metadata:
  name: home
  labels:
    app.kubernetes.io/managed-by: towonel-operator
    app.kubernetes.io/part-of: towonel-operator
spec:
  tunnelRef:
    name: main
    namespace: towonel
  workload:
    image: codeberg.org/towonel/towonel-agent:0.2.1@sha256:761c9fbc716624dd941d80f21d4e82f94d631942cd9e0a2d3affa92cf25eacd9
