---
apiVersion: towonel.io/v1alpha1
kind: TowonelAgent
metadata:
  name: external
spec:
  tunnelRef:
    name: towonel
    namespace: towonel
  # TODO: forward UDP/31820
  connectivity:
    autodiscover: true
    irohPort: 51820
    nodePort:
      create: true
      port: 31820
  workload:
    image: codeberg.org/towonel/towonel-agent:0.1.32
