---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.0
    digest: sha256:2d3493dd4ba981bd001fcd0c2a57b131dc38e4ce064ef06f27571be2e4f28c75
  url: oci://ghcr.io/kgateway-dev/charts/kgateway
