---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.3
    digest: sha256:08a0e42a5946bfbd9bc4617ba8557ee6901e46058a74148570e8b3a417f15f5e
  url: oci://ghcr.io/kgateway-dev/charts/kgateway
