---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.2/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.3.6
    digest: sha256:c648339d780b87bf815c56d5e8af1b7303b22b36008c2165d75d71bf72f4ee06
  url: oci://ghcr.io/kgateway-dev/charts/kgateway
