---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-rules
  namespace: flux-system
spec:
  targetNamespace: node-feature-discovery
  dependsOn:
    - name: node-feature-discovery
  sourceRef:
    kind: OCIRepository
    name: node-feature-discovery
  path: ./rules
  commonMetadata:
    labels:
      app.kubernetes.io/name: node-feature-discovery
