---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id-operator
  namespace: flux-system
spec:
  targetNamespace: pocket-id-operator
  dependsOn:
    - name: pocket-id-operator-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/pocket-id-operator/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: pocket-id-operator
