---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mcp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.25.3
    digest: sha256:34fa35e181c0ef8b14d6752af0ce4b07716c0604ddbe8effa3d026f36d80ee3d
  url: oci://ghcr.io/grafana-community/helm-charts/grafana-mcp
