---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mcp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.23.0
    digest: sha256:ef44c00cf93c72252506d5234440a9f720483b0e2de47d2449dc069eeaa64a91
  url: oci://ghcr.io/grafana-community/helm-charts/grafana-mcp
