---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mcp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.23.2
    digest: sha256:b97ee10e59c1a833471159f975dd1b75d584a5b0f17d187c7c6ae90a16e139b6
  url: oci://ghcr.io/grafana-community/helm-charts/grafana-mcp
