---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  targetNamespace: zigbee2mqtt
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/zigbee2mqtt/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: zigbee2mqtt
