---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.3/helmrelease_v2.json?values=app-template/4.6.2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      wg-easy:
        pod:
          securityContext:
            seccompProfile: { type: RuntimeDefault }
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: 15.2.2@sha256:cf815209439101842f81d62bb25f7d66140e4cf8c100b4de5d0e84569d38732a
            env:
              DISABLE_IPV6: true
              INIT_ENABLED: true
              INIT_USERNAME:
                secretKeyRef:
                  name: wg-easy
                  key: username
              INIT_PASSWORD:
                secretKeyRef:
                  name: wg-easy
                  key: password
              INIT_HOST: wireguard.${SECRET_DOMAIN}
              INIT_DNS: 172.17.0.11
            resources:
              requests:
                cpu: 15m
                memory: 15Mi
              limits:
                memory: 256Mi
                squat.ai/tun: 1
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_ADMIN
    service:
      vpn:
        controller: wg-easy
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.38.55.60
          external-dns.alpha.kubernetes.io/hostname: wg-easy.${SECRET_DOMAIN}
        ports:
          http:
            port: 51820
            protocol: UDP
      ui:
        controller: wg-easy
        ports:
          http:
            port: 51821
    route:
      wg-easy:
        hostnames:
          - wg-easy.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: gateway-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: wg-easy
                port: 51821
    persistence:
      config:
        existingClaim: wg-easy
        globalMounts:
          - path: /etc/wireguard
