---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-vpn
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wireguard.${SECRET_DOMAIN}
spec:
  clusterIP: None
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
      targetPort: 51820
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: wg-easy-vpn
  labels:
    kubernetes.io/service-name: wg-easy-vpn
addressType: IPv4
ports:
  - name: wireguard
    port: 51820
    protocol: UDP
endpoints:
  - addresses:
      - 10.0.30.60
