---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.2-standalone-strict/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${POOL}-zfs-scrubber
spec:
  schedule: "${SCRUB_SCHEDULE}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: "bonds"
          containers:
            - name: zfs-scrubber
              image: ghcr.io/heavybullets8/zfs-scrubber:1.1.1@sha256:d5c3fd2edfa5fa2b054e24411d79ecbe7bd6bd76547ff59e08ae2926338a2ddd
              env:
                - name: ACTION
                  value: "scrub"
                - name: ZFS_POOL
                  value: "${POOL}"
                - name: PUSHOVER_NOTIFICATION
                  value: "false"
                - name: TALOS_VERSION
                  value: "${TALOS_VERSION}"
              securityContext:
                privileged: true
              volumeMounts:
                - name: dev
                  mountPath: /dev/zfs
          restartPolicy: Never
          volumes:
            - name: dev
              hostPath:
                path: /dev/zfs
