---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.0
    digest: sha256:15f455c6fd7a22eea50a5da179d25a2aa89f1ac4a84a206eb96e4d747f18c747
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
