---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.4/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.2
    digest: sha256:d5fd956f728a5181e58eeae03c9f8b66a3f74359d6cdf7c615df954fb407d48c
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
