---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/towonel-operator/1.0.1/towoneltunnel_v1alpha1.json
apiVersion: towonel.io/v1alpha1
kind: TowonelTunnel
metadata:
  name: raphael-k8s
spec:
  region: CA
  deletionPolicy: Delete
  tokenExpiry: 0
  extraHostnames:
    - "raphael.clerici.tech"
    - "*.raphael.clerici.tech"
