---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: omada-controller
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.5.3
    digest: sha256:c5a4fc6c55fdf90121f7ef5eb921aff6d204343008f8119e00d03649c9d5f5b0
  url: oci://mirror.gcr.io/mbentley/omada-controller-helm
