---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: omada-controller
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.4.1
    digest: sha256:02582ed10b0b94dc4230605c181d79b4bd20cd8a24f1d058029468b097a1200e
  url: oci://mirror.gcr.io/mbentley/omada-controller-helm
