---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.5/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: omada-controller
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.5.2
    digest: sha256:55c650852a7dc752bdbe14c91d12fd73368ef4e2af0ad0962d33bc5f883c29d5
  url: oci://mirror.gcr.io/mbentley/omada-controller-helm
