---
machine:
  features:
    rbac: true
    stableHostname: false
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
---
apiVersion: v1alpha1
kind: ResolverConfig
hostDNS:
  enabled: false
  forwardKubeDNSToHost: false
  resolveMemberNames: false
