---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/prometheus-operator/0.93.1/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
spec:
  jobLabel: envoy-gateway
  namespaceSelector:
    matchNames:
      - envoy-gateway
  selector:
    matchLabels:
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
