---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: drm-exporter
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.5
    digest: sha256:29322450dac166f2bf95d2e5291f21d8cf8e90b361b6f2afb839095fa2b01cdb
  url: oci://ghcr.io/home-operations/charts/drm-exporter
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/drm-exporter.*$"
