---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.2/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: generic-device-plugin
spec:
  interval: 30m
  url: https://github.com/aclerici38/generic-device-plugin.git
  ref:
    branch: chart/more-config
  ignore: |-
    /*
    !/charts/generic-device-plugin
