---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
  namespace: k8tz
spec:
  interval: 1h
  targetNamespace: k8tz
  chart:
    spec:
      chart: ./kubernetes/apps/k8tz
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    timeout: 5m
    crds: CreateReplace
    remediation:
      retries: 1
  upgrade:
    timeout: 5m
    crds: CreateReplace
    remediation:
      retries: 1
