---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  targetNamespace: home-assistant
  sourceRef:
    kind: OCIRepository
    name: home-assistant
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: home-assistant
