---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager external-secrets intel-gpu-resource-driver k8tz node-feature-discovery onepassword-connect reloader smtp-relay spegel
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cert-manager external-secrets intel-gpu-resource-driver k8tz node-feature-discovery onepassword-connect reloader smtp-relay spegel
    oci.home/managed: "true"
spec:
  interval: 1h
  url: oci://ghcr.io/aclerici38/home-ops/cert-manager external-secrets intel-gpu-resource-driver k8tz node-feature-discovery onepassword-connect reloader smtp-relay spegel
  ref:
    tag: main
  layerSelector:
    mediaType: application/vnd.cncf.flux.content.v1.tar+gzip
    operation: extract
