---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefox
  namespace: flux-system
spec:
  targetNamespace: firefox
  sourceRef:
    kind: OCIRepository
    name: firefox
  path: ./app
  commonMetadata:
    labels:
      app.kubernetes.io/name: firefox
