---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.2/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: long-smart-tester
  namespace: flux-system
spec:
  targetNamespace: smart-tester
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/smart-tester/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: smart-tester
  postBuild:
    substitute:
      TEST_TYPE: long
      TEST_SCHEDULE: "0 2 3 * *"
