---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  targetNamespace: onepassword-connect
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/shared/onepassword-connect/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
