---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-proxy-crowdsec-bouncer
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.1
    digest: sha256:3651a55dad58a0b43da3d18b6fad9e6f3b4374d73a057ead1a5b911e6930d1d9
  url: oci://ghcr.io/kdwils/charts/envoy-proxy-bouncer
