---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller/namespace.yaml
  - ./actions-runner-controller/controller.yaml
  - ./actions-runner-controller/runners.yaml
  - ./actual/namespace.yaml
  - ./actual/app.yaml
  - ./airconnect/namespace.yaml
  - ./airconnect/app.yaml
  - ./atuin/namespace.yaml
  - ./atuin/app.yaml
  - ./bazarr/namespace.yaml
  - ./bazarr/app.yaml
  - ./blocky/namespace.yaml
  - ./blocky/app.yaml
  - ./blocky/blocky-ui.yaml
  - ./browserless/namespace.yaml
  - ./browserless/app.yaml
  - ./cert-manager/namespace.yaml
  - ./cert-manager/app.yaml
  - ./cert-manager/clusterissuers.yaml
  - ./cilium/namespace.yaml
  - ./cilium/app.yaml
  - ./cilium/networking.yaml
  - ./cloudnative-pg/namespace.yaml
  - ./cloudnative-pg/app.yaml
  - ./cloudnative-pg/catalogs.yaml
  - ./cloudnative-pg/plugin-barman-cloud.yaml
  - ./convertx/namespace.yaml
  - ./convertx/app.yaml
  - ./crowdsec/namespace.yaml
  - ./crowdsec/app.yaml
  - ./csi-driver-nfs/namespace.yaml
  - ./csi-driver-nfs/app.yaml
  - ./dawarich/namespace.yaml
  - ./dawarich/app.yaml
  - ./donetick/namespace.yaml
  - ./donetick/app.yaml
  - ./envoy-proxy-crowdsec-bouncer/namespace.yaml
  - ./envoy-proxy-crowdsec-bouncer/app.yaml
  - ./filebrowser/namespace.yaml
  - ./filebrowser/app.yaml
  - ./firefox/namespace.yaml
  - ./firefox/app.yaml
  - ./flaresolverr/namespace.yaml
  - ./flaresolverr/app.yaml
  - ./flux-system/namespace.yaml
  - ./flux-system/flux-instance.yaml
  - ./flux-system/flux-operator.yaml
  - ./frigate/namespace.yaml
  - ./frigate/app.yaml
  - ./home-assistant/namespace.yaml
  - ./home-assistant/app.yaml
  - ./homebox/namespace.yaml
  - ./homebox/app.yaml
  - ./immich/namespace.yaml
  - ./immich/app.yaml
  - ./immich-kiosk/namespace.yaml
  - ./immich-kiosk/app.yaml
  - ./intel-gpu-resource-driver/namespace.yaml
  - ./intel-gpu-resource-driver/app.yaml
  - ./it-tools/namespace.yaml
  - ./it-tools/app.yaml
  - ./jellyfin/namespace.yaml
  - ./jellyfin/app.yaml
  - ./k8s-gateway/namespace.yaml
  - ./k8s-gateway/app.yaml
  - ./karakeep/namespace.yaml
  - ./karakeep/app.yaml
  - ./matter-server/namespace.yaml
  - ./matter-server/app.yaml
  - ./mealie/namespace.yaml
  - ./mealie/app.yaml
  - ./mosquitto/namespace.yaml
  - ./mosquitto/app.yaml
  - ./multus/namespace.yaml
  - ./multus/app.yaml
  - ./multus/networks.yaml
  - ./nats-opencloud/namespace.yaml
  - ./nats-opencloud/app.yaml
  - ./nfs-server/namespace.yaml
  - ./nfs-server/app.yaml
  - ./node-feature-discovery/namespace.yaml
  - ./node-feature-discovery/app.yaml
  - ./node-feature-discovery/rules.yaml
  - ./octoprint/namespace.yaml
  - ./octoprint/app.yaml
  - ./omada-controller/namespace.yaml
  - ./omada-controller/app.yaml
  - ./omada-controller/exporter.yaml
  - ./omnitools/namespace.yaml
  - ./omnitools/app.yaml
  - ./open-webui/namespace.yaml
  - ./open-webui/app.yaml
  - ./opencloud/namespace.yaml
  - ./opencloud/app.yaml
  - ./openebs-system/namespace.yaml
  - ./openebs-system/app.yaml
  - ./openebs-system/zfs-volumes.yaml
  - ./otbr/namespace.yaml
  - ./otbr/app.yaml
  - ./pocket-id-operator/namespace.yaml
  - ./pocket-id-operator/app.yaml
  - ./prowlarr/namespace.yaml
  - ./prowlarr/app.yaml
  - ./qbittorrent/namespace.yaml
  - ./qbittorrent/app.yaml
  - ./radarr/namespace.yaml
  - ./radarr/app.yaml
  - ./recyclarr/namespace.yaml
  - ./recyclarr/app.yaml
  - ./rook-ceph/namespace.yaml
  - ./rook-ceph/app.yaml
  - ./rook-ceph/cluster.yaml
  - ./samba/namespace.yaml
  - ./samba/app.yaml
  - ./scrutiny/namespace.yaml
  - ./scrutiny/app.yaml
  - ./searxng/namespace.yaml
  - ./searxng/app.yaml
  - ./seerr/namespace.yaml
  - ./seerr/app.yaml
  - ./smart-tester/namespace.yaml
  - ./smart-tester/long.yaml
  - ./smart-tester/short.yaml
  - ./smartctl-exporter/namespace.yaml
  - ./smartctl-exporter/app.yaml
  - ./smtp-relay/namespace.yaml
  - ./smtp-relay/app.yaml
  - ./snapshot-controller/namespace.yaml
  - ./snapshot-controller/app.yaml
  - ./sonarr/namespace.yaml
  - ./sonarr/app.yaml
  - ./speedtest-exporter/namespace.yaml
  - ./speedtest-exporter/app.yaml
  - ./spegel/namespace.yaml
  - ./spegel/app.yaml
  - ./streamystats/namespace.yaml
  - ./streamystats/app.yaml
  - ./tika/namespace.yaml
  - ./tika/app.yaml
  - ./towonel-operator/namespace.yaml
  - ./towonel-operator/config.yaml
  - ./towonel-operator/operator.yaml
  - ./trek/namespace.yaml
  - ./trek/app.yaml
  - ./tuppr/namespace.yaml
  - ./tuppr/app.yaml
  - ./tuppr/upgrades.yaml
  - ./versity/namespace.yaml
  - ./versity/app.yaml
  - ./volsync/namespace.yaml
  - ./volsync/app.yaml
  - ./volsync/kopia.yaml
  - ./vuetorrent/namespace.yaml
  - ./vuetorrent/app.yaml
  - ./wyoming-piper/namespace.yaml
  - ./wyoming-piper/app.yaml
  - ./wyoming-whisper/namespace.yaml
  - ./wyoming-whisper/app.yaml
  - ./zfdash/namespace.yaml
  - ./zfdash/app.yaml
  - ./zfs-scrubber/namespace.yaml
  - ./zfs-scrubber/ssd.yaml
  - ./zfs-scrubber/tank.yaml
  - ./zigbee2mqtt/namespace.yaml
  - ./zigbee2mqtt/app.yaml
