---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr
spec:
  targetNamespace: tuppr
  path: ./kubernetes/apps/tuppr/tuppr/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: tuppr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-upgrades
spec:
  targetNamespace: tuppr
  dependsOn:
    - name: tuppr
  path: ./kubernetes/apps/tuppr/tuppr/upgrades
  commonMetadata:
    labels:
      app.kubernetes.io/name: tuppr
