---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: konflate
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.32
    digest: sha256:c3c77b7f3fdcf4fdfaf7632927b37aa1744a9318b0bda8de4b0cdeb8f82db360
  url: oci://ghcr.io/home-operations/charts/konflate
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/home-operations/konflate/\.github/workflows/release\.yaml@refs/tags/.*$
