---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/grafana-operator/5.25.0/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  version: mirror.gcr.io/grafana/grafana:13.2.0@sha256:3fd54ae1214669f8355f065ec9f6445d5279a3d77095ab048ca045685272429b
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: Pocket ID
      allow_sign_up: "true"
      auto_login: "true"
      use_pkce: "true"
      scopes: openid email profile groups
      role_attribute_path: "'Admin'"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.${CLUSTER_NAME}.clerici.tech
  httpRoute:
    spec:
      hostnames:
        - grafana.${CLUSTER_NAME}.clerici.tech
      parentRefs:
        - name: internal
          namespace: envoy-gateway
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator
                      key: password
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-oidc-credentials
                      key: client_id
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-oidc-credentials
                      key: client_secret
                - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-oidc-credentials
                      key: authorization_url
                - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-oidc-credentials
                      key: token_url
                - name: GF_AUTH_GENERIC_OAUTH_API_URL
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-oidc-credentials
                      key: userinfo_url
                - name: GF_AUTH_SIGNOUT_REDIRECT_URL
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-oidc-credentials
                      key: end_session_url
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: ceph-block
  disableDefaultSecurityContext: All
