---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.6/helmrelease_v2.json?values=app-template/4.6.2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrutiny
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      scrutiny:
        containers:
          scrutiny:
            image:
              repository: ghcr.io/analogj/scrutiny
              tag: v0.9.1-web@sha256:a758d2846ed51e43f2b4e36f42e8760899a75f9383884d7849dc0f04d9fd83a1
            env:
              SCRUTINY_WEB_INFLUXDB_HOST: scrutiny-influxdb
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 8080
              readiness: *probes
            securityContext: &sec
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 20Mi
              limits:
                memory: 128Mi
      influxdb:
        containers:
          influxdb:
            image:
              repository: mirror.gcr.io/library/influxdb
              tag: 2.8.0-alpine@sha256:4f90d40c00193d91889ad872c39a586a011db4ac4d1a766e248d9cbbcc6cec3e
            probes:
              liveness: &dbProbes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    port: &dbPort 8086
                    path: /health
              readiness: *dbProbes
            resources:
              requests:
                cpu: 100m
                memory: 20Mi
              limits:
                memory: 512Mi
            securityContext: *sec
      collector:
        type: daemonset
        containers:
          scrutiny-collector:
            image:
              repository: ghcr.io/analogj/scrutiny
              tag: v0.9.1-collector@sha256:6c238e9996e8b19dc64916d32d2a0be1dc0619907fc107d7d437f8a5be8449ac
            env:
              COLLECTOR_RUN_STARTUP: true
              COLLECTOR_API_ENDPOINT: "http://scrutiny:8080"
              COLLECTOR_CRON_SCHEDULE: "0 * * * *"
              COLLECTOR_HOST_ID:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 100m
                memory: 10Mi
              limits:
                memory: 128Mi
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
                add: ["SYS_RAWIO", "SYS_ADMIN", "SETUID", "SETGID"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      scrutiny:
        controller: scrutiny
        ports:
          http:
            port: *port
      influxdb:
        controller: influxdb
        ports:
          http:
            port: *dbPort
    route:
      scrutiny:
        hostnames:
          - ${APP_URL}
        parentRefs:
          - name: internal
            namespace: gateway-system
        rules:
          - backendRefs:
            - identifier: scrutiny
              port: *port
    persistence:
      config:
        existingClaim: scrutiny
        advancedMounts:
          scrutiny:
            scrutiny:
              - path: /opt/scrutiny/config
                subPath: scrutiny
          influxdb:
            influxdb:
              - path: /var/lib/influxdb2
                subPath: influxdb
      udev:
        type: hostPath
        hostPath: /run/udev
        advancedMounts:
          collector:
            scrutiny-collector:
              - path: /run/udev
                readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        advancedMounts:
          collector:
            scrutiny-collector:
              - path: /dev
