---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/cloudnative-pg/0.27.1/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recovery-patch
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'
spec:
  bootstrap:
    recovery:
      source: ${APP}-db
  externalClusters:
    - name: ${APP}-db
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: ${APP}
          serverName: ${APP}-db
