---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/kgateway/2.2.2/backend_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: ${APP}-oauth-backend
spec:
  type: Static
  static:
    hosts:
      - host: pocket-id.home-infra.svc.cluster.local
        port: 1411
