---
base:
  controllers:
    qbittorrent:
      pod:
        securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: {type: RuntimeDefault}
      initContainers:
        gluetun:
          lifecycle:
            postStart:
              exec:
                # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/kubernetes.md#adding-ipv6-rule--file-exists
                command:
                  - "/bin/sh"
                  - "-c"
                  - "(ip rule del table 51820; ip -6 rule del table 51820) || true"
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
          env:
            LOG_LEVEL: debug
            VPN_SERVICE_PROVIDER: custom
            VPN_TYPE: wireguard
            VPN_INTERFACE: wg0
            WIREGUARD_ENDPOINT_PORT: 51820
            VPN_PORT_FORWARDING: "on"
            VPN_PORT_FORWARDING_PROVIDER: protonvpn
            FIREWALL_INPUT_PORTS: &port 8080
            FIREWALL_OUTBOUND_SUBNETS: ${CLUSTER_POD_CIDR},${CLUSTER_SVC_CIDR}
            VPN_PORT_FORWARDING_UP_COMMAND: '/bin/sh -c ''wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":{{ `{{PORT}}` }},\"current_network_interface\":\"{{ `{{VPN_INTERFACE}}` }}\",\"random_port\":false,\"upnp\":false}" http://127.0.0.1:8080/api/v2/app/setPreferences'''
            VPN_PORT_FORWARDING_DOWN_COMMAND: '/bin/sh -c ''wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http://127.0.0.1:8080/api/v2/app/setPreferences'''
          resources:
            limits:
              devic.es/tun: 1
          restartPolicy: Always
          envFrom:
            - secretRef:
                name: qbittorrent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_ADMIN
                - CHOWN
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      containers:
        qbittorrent:
          image:
            repository: ghcr.io/home-operations/qbittorrent
            tag: 5.2.1@sha256:8d58d9ad18a1fb5e556e68bde7ac06046847cc97069257f01d2e1ec0d27ff019
          resources:
            requests:
              cpu: 49m
              memory: 1024Mi
            limits:
              memory: 6000Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          probes:
            liveness: &probes
              enabled: true
              type: HTTP
              port: *port
            readiness: *probes
  service:
    qbittorrent:
      controller: qbittorrent
      ports:
        http:
          port: *port
  persistence:
    config:
      existingClaim: qbittorrent
      advancedMounts:
        qbittorrent:
          qbittorrent:
            - path: /config
    tmp:
      type: emptyDir
      advancedMounts:
        qbittorrent:
          gluetun:
            - path: /tmp/gluetun
    media:
      type: nfs
      server: nfs.clerici.tech
      path: /media
      advancedMounts:
        qbittorrent:
          qbittorrent:
            - path: /allMedia
