# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.5/helmrelease_v2.json?values=flux-operator/0.45.1
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  valuesFrom:
    - kind: Secret
      name: flux-operator-oidc-credentials
      valuesKey: client_secret
      targetPath: web.config.authentication.oauth2.clientSecret
    - kind: Secret
      name: flux-operator-oidc-credentials
      valuesKey: client_id
      targetPath: web.config.authentication.oauth2.clientID
  values:
    serviceMonitor:
      create: true
    installCRDs: true
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
      seccompProfile:
        type: "RuntimeDefault"
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 64Mi
    web:
      networkPolicy:
        create: false
      config:
        baseURL: https://flux.${SECRET_DOMAIN}
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            issuerURL: https://id.${SECRET_DOMAIN}
            scopes:
              - openid
              - profile
              - email
              - groups
            impersonation:
              groups: "['system:masters']"
      httpRoute:
          enabled: true
          parentRefs:
            - name: internal
              namespace: gateway-system
              sectionName: https
          hostnames:
            - flux.${SECRET_DOMAIN}

