# yaml-language-server: $schema=https://flux2-schemas.pages.dev/helmrelease/v2/github/controlplaneio-fluxcd/charts/0.43.0/charts/flux-operator
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  valuesFrom:
    - kind: ConfigMap
      name: flux-operator-helm-values
    - kind: Secret
      name: flux-operator-oidc-credentials
      valuesKey: client_secret
      targetPath: web.config.authentication.oauth2.clientSecret
    - kind: Secret
      name: flux-operator-oidc-credentials
      valuesKey: client_id
      targetPath: web.config.authentication.oauth2.clientId
  values:
    web:
      config:
        baseURL: https://flux.example.com
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            issuerURL: https://id.${SECRET_DOMAIN}
            scopes:
              - openid
              - profile
              - email
              - groups
            claims:
              impersonation:
                groups: "['system:masters']"

