---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.8/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.3.3
    digest: sha256:d6c56449071f5d969a499ba724308269f6cec8962b39d04247a4db0b145a9022
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
