---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: Extensions
      name: cnpg-extensions
      fieldPath: spec.extensions
    targets:
      - select:
          kind: Cluster
          group: postgresql.cnpg.io
        fieldPaths:
          - spec.postgresql.extensions
