---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/renovate-operator/4.5.1/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: ${NAME}
spec:
  provider:
    name: github
  discoveryFilters:
    - /aclerici38\/(${REPOS})/
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: >-
        [
          "pnpm run bundle"
        ]
    - name: RENOVATE_PLATFORM_COMMIT
      value: enabled
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: renovate-operator
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-operator
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [
          {
            "hostType": "docker",
            "matchHost": "docker.io",
            "username": "$(DOCKERHUB_USERNAME)",
            "password": "$(DOCKERHUB_TOKEN)"
          }
        ]
    - name: RENOVATE_REDIS_URL
      value: redis://renovate-operator-dragonfly-db:6379
    - name: RENOVATE_REPOSITORY_CACHE
      value: enabled
    - name: RENOVATE_CACHE_PRIVATE_PACKAGES
      value: "true"
  image: ghcr.io/renovatebot/renovate:43.159.2@sha256:48d2ec31e7b9255e30eef20b23d2370984c4e2a048cc02cfd7a05f32be802d24
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "${SCHEDULE}"
  secretRef: botthebuilder-auth
