---
base:
  app-template:
    enabled: false

intel-gpu-resource-driver:
  cdi:
    staticPath: /var/cdi/static
    dynamicPath: /var/cdi/dynamic
  kubeletPlugin:
    privileged: true
    healthMonitoring:
      enabled: false
