---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/cilium/1.19.2/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
  namespace: ${NS}
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: 10.38.55.0/24
---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/cilium/1.19.2/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lab-pool"
  namespace: ${NS}
spec:
  allowFirstLastIPs: 'Yes'
  blocks:
    - start: 10.0.30.200
      stop: 10.0.30.250
