---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: samba
  namespace: flux-system
spec:
  targetNamespace: samba
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home/samba/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: samba
