---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.1/helmrelease_v2.json?values=app-template/5.0.1
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky-ui
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  dependsOn:
    - name: blocky-resources
  values:
    controllers:
      blocky-ui:
        strategy: RollingUpdate
        pod:
          hostUsers: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile: {type: RuntimeDefault}
        containers:
          blocky-ui:
            image:
              repository: ghcr.io/gabeduartem/blocky-ui
              tag: 1.9.1@sha256:43de7e9c84ae01e00c674ea7aefaa2a0a5801ce4ab6bc29e961c0aee0d6cfce1
            env:
              QUERY_LOG_TYPE: postgresql
              QUERY_LOG_TARGET:
                secretKeyRef:
                  name: blocky-postgres
                  key: uri
              BLOCKY_API_URL: http://blocky-k8s.blocky:4000
            probes:
              liveness:
                enabled: true
                type: HTTP
              readiness:
                enabled: true
                type: HTTP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      blocky-ui:
        controller: blocky-ui
        ports:
          http:
            port: 3000
    route:
      blocky-ui:
        hostnames:
          - blocky.clerici.tech
        parentRefs:
          - name: internal
            namespace: kgateway
