---
apiVersion: v2
name: generic-device-plugin
version: 0.0.0
dependencies:
  - name: base
    version: 0.0.0
    repository: file://../../charts/base
  # temp until https://github.com/squat/generic-device-plugin/pull/206
  - name: generic-device-plugin
    version: 0.2.0
    repository: oci://docker.io/ant385525
