---
base:
  app-template:
    enabled: false

reloader:
  reloader:
    autoReloadAll: true
    watchGlobally: true
    enableCSIIntegration: true
    enableMetricsByNamespace: true
    ignoreNamespaces: "cilium,rook-ceph,kube-system"
    readOnlyRootFileSystem: true
    serviceMonitor:
      enabled: true
      