---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.3/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
spec:
  interval: 30m
  prune: false
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: ./config/crd
