---
base:
  app-template:
    enabled: false

k8tz:
  createNamespace: false
  replicaCount: 2
  timezone: ${TZ}
  cronJobTimeZone: true
  webhook:
    failurePolicy: Ignore
    ignoredNamespaces:
      - cilium
      - kube-system
      - multus
    certManager:
      enabled: true
      issuerRef:
        name: k8tz-webhook-selfsign
        kind: Issuer
