---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.1/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.12.3
    digest: sha256:a2836f9c7e9376e1e7eb0a9693cd7c4a8fb42faccc4fe88c87f2706584e0183c
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
