---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.9.0
    digest: sha256:6e84aaa01e89cfa16fed068684247650e4d56d69f2eae666fd185f29628d30fa
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
