---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.0/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.4.0
    digest: sha256:e94bd2523dce6f3fecfbe70f5b7dab5a865047467f477c0d526f66c39d5cf848
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
