---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.5/helmrelease_v2.json?values=app-template/4.6.2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-whisper
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 5m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      wyoming-whisper:
        strategy: RollingUpdate
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: wyoming-whisper-gpu
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile: { type: RuntimeDefault }
        containers:
          whisper:
            image:
              repository: ghcr.io/sjtrny/wyoming-whisper-intel
              tag: release@sha256:518e804b7464856b9506e48260047aad68732cb1e19b4331067be0414e455def
            env:
              ONEAPI_DEVICE_SELECTOR: "level_zero:gpu"
              ZE_ENABLE_PCI_ID_DEVICE_ORDER: "1"
              WHISPER_MODEL: large-v3-turbo
              WHISPER_LANG: en
              WHISPER_BEAM_SIZE: "5"
              WHISPER_HTTP_HOST: "127.0.0.1"
              WHISPER_HTTP_PORT: "8910"
              WYOMING_URI: tcp://0.0.0.0:10300
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi
              claims:
                - name: gpu
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
    service:
      wyoming-whisper:
        controller: wyoming-whisper
        ports:
          wyoming:
            port: 10300
    persistence:
      models:
        existingClaim: wyoming-whisper-cache
        globalMounts:
          - path: /models
