---
# `customization` is reserved
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: 20-customization
content: |
  [plugins."io.containerd.cri.v1.images"]
    discard_unpacked_layers = false
  [plugins."io.containerd.cri.v1.runtime"]
    device_ownership_from_security_context = true
    cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
---
apiVersion: v1alpha1
kind: EtcFileConfig
name: nfsmount.conf
mode: 0o644
contents: |-
  [ NFSMount_Global_Options ]
  nfsvers=4.2
  proto=tcp
  softerr=True
  timeo=10
  retrans=2
  nconnect=16
  rsize=1048576
  wsize=1048576
  noatime=True
