---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.1/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  dependsOn:
    - name: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/raphael/external-secrets/stores
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-secrets
