---
base:
  app-template:
    enabled: false

k8s-gateway:
  domain: clerici.tech
  fallthrough:
    enabled: true
    zones:
      - clerici.tech
  replicaCount: 2
  watchedResources:
    - HTTPRoute
    - Service
  extraZonePlugins:
    - name: log
    - name: errors
    - name: health
      configBlock: |-
        lameduck 5s
    - name: ready
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . 1.1.1.1
  service:
    type: ClusterIP
    clusterIP: ""
  debug:
    enabled: true
  serviceAccount:
    create: true
    name: k8s-gateway
