---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats-opencloud
spec:
  interval: 1h
  maxHistory: 1
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
      version: 2.12.4
  install:
    timeout: 2m
  upgrade:
    timeout: 2m
  values:
    config:
      cluster:
        enabled: true
        replicas: 3
        merge:
          name: opencloud-cluster
      jetstream:
        enabled: true
        fileStore:
          pvc:
            size: &pvc 10Gi
            storageClassName: ceph-filesystem
          maxSize: *pvc
        memoryStore:
          enabled: true
          maxSize: &mem 256Mi
    natsBox:
      enabled: false
    container:
      env:
        # Should be ~80% of memory limit
        GOMEMLIMIT: 410MiB
      merge:
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 512Mi
    podTemplate:
      topologySpreadConstraints:
        kubernetes.io/hostname:
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
    