---
base:
  cnpg:
    enabled: true
    mode: restore

  externalSecret:
    enabled: true

  host: radarr.clerici.tech

  image:
    repository: ghcr.io/home-operations/radarr
    tag: 6.2.0.10390@sha256:be596a2f896fdf15077af027f44500f73e1f6fb7b450a6494b37dd25b7cc5927
  ports:
    http: 7878
  env:
    RADARR__APP__INSTANCENAME: Radarr
    RADARR__APP__THEME: dark
    RADARR__AUTH__METHOD: External
    RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
    RADARR__LOG__DBENABLED: "False"
    RADARR__LOG__LEVEL: info
    RADARR__SERVER__PORT: 7878
    RADARR__POSTGRES__HOST:
      valueFrom:
        secretKeyRef:
          name: radarr-db-app
          key: pooler-host
    RADARR__POSTGRES__USER:
      valueFrom:
        secretKeyRef:
          name: radarr-db-app
          key: username
    RADARR__POSTGRES__PASSWORD:
      valueFrom:
        secretKeyRef:
          name: radarr-db-app
          key: password
    RADARR__POSTGRES__MAINDB:
      valueFrom:
        secretKeyRef:
          name: radarr-db-app
          key: dbname
  envFrom:
    - secretRef:
        name: radarr
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /ping
          port: 7878
    readiness: *probes
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 4Gi
  persistence:
    tmpfs:
      type: emptyDir
      globalMounts:
        - path: /tmp
          subPath: tmp
        - path: /config
          subPath: config
    media:
      type: nfs
      server: nfs.clerici.tech
      path: /media
      globalMounts:
        - path: /allMedia
