---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.9.4/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi-operator
spec:
  interval: 15m
  url: https://ceph.github.io/ceph-csi-operator
