---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Nix

on:
  push:
    branches:
      - "main"
    paths:
      - "nix-config/**"
      - "raphael/**"
      - ".github/workflows/nix.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "nix-config/**"
      - "raphael/**"
      - ".github/workflows/nix.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          determinate: false

      - name: nixfmt
        run: nix shell nixpkgs#nixfmt --command nixfmt --check nix-config/*.nix raphael/*.nix raphael/nixos/*.nix

      - name: statix
        run: |
          nix shell nixpkgs#statix --command statix check -c nix-config nix-config
          nix shell nixpkgs#statix --command statix check -c nix-config raphael

      - name: deadnix
        run: nix shell nixpkgs#deadnix --command deadnix --fail nix-config raphael

  flake-checker:
    name: Flake Health
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Flake Checker
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
        with:
          flake-lock-path: nix-config/flake.lock
          fail-mode: true

      - name: Flake Checker (raphael)
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
        with:
          flake-lock-path: raphael/flake.lock
          fail-mode: true

  success:
    if: ${{ !cancelled() }}
    needs:
      - "lint"
      - "flake-checker"
    name: Nix - Success
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
